### PR TITLE
add namespace support

### PR DESCRIPTION
**Pull request by n1crack**
Since there are a lot of people use modules, even some of the famous packages has their own namespaced lang files, it seems namespace support is needed. There are also some related topics in the discussions.

Feel free to reject the PR, but somehow make the namespace support available to us pls :)

### CODE REVIEW

**Comment by bilogic** [comment]
nice!

**Comment by n1crack** [comment]
https://github.com/spatie/laravel-translation-loader/discussions/144

https://github.com/spatie/laravel-translation-loader/discussions/168

**Comment by bilogic** [comment]
haha thanks, it was such pure coincidence that you made this PR, we managed to find the root cause yesterday after quite a bit of work

**Comment by n1crack** [comment]
I don't get it if you are sarcastic, as english is not my native, still I understand you had quite work on that, there is a PR below from 2017 (yes almost 7 years ago).
https://github.com/spatie/laravel-translation-loader/pull/46/files

I thought it would be nice if I bring this as a PR, and I don't need any credit for this. I just need it for my projects.

**Comment by bilogic** [comment]
@n1crack 

Not sarcastic towards you. I'm very grateful you made this PR!

**Comment by n1crack** [comment]
Im closing this, well it's not likely to going to be merged anyway. I'll use my own fork.

**Comment by AlexisSerneels** [comment]
I like this PR anyway. I don't see any reason it was closed.

**Comment by n1crack** [comment]
It was closed because I needed the changes and wait more than 1 month. And decided to use my own fork. 

Hope, someone else make this happen. I'd be glad.

**Comment by n1crack** [comment]
Why would I :). feel free to use it

btw im not Belgian, one of my Belgian friends make me buy the domain :)

**Pull request closed without merging**
