### PR TITLE
Update create_language_lines_table.php.stub

### PR DESCRIPTION
**Pull request by hannah-massey**

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by fredsal** [comment]
This breaks the tests

**Comment by fredsal** [comment]
This breaks the tests
@freekmurze breaks compatibility 

https://github.com/spatie/laravel-translation-loader/blob/ca3267c14d9363ddebb4bf381fbeaca813148050/tests/TestCase.php#L21-L23

https://github.com/spatie/laravel-translation-loader/blob/ca3267c14d9363ddebb4bf381fbeaca813148050/composer.json#L26

**Comment by freekmurze** [comment]
@fredsal fixed by @erikn69 🙌

**Pull request merged**
