### PR TITLE
Fixes Laravel 5.5+ auto discovery issues

### PR DESCRIPTION
**Pull request by mojtabaahn**

### CODE REVIEW

**Comment by freekmurze** [comment]
Which problem is this PR trying to solve?

**Comment by mojtabaahn** [comment]
Sorry for lack of description. There is already an issue about it #80 ; I just realized. 
In short If we install the package with Laravel5.5+, and we already have and used some translations in our project, it will try to use `DB` TranslationLoader and fails because _language_lines_ table doesn't exists yet.

**Comment by freekmurze** [comment]
What I don't like about this implementation is that it will execute a query every time the app is booting.

**Comment by mojtabaahn** [comment]
I agree. What about adding an option to deactivate registration in config?

**Pull request closed without merging**
