### PR TITLE
Update TranslationLoaderManager.php

### PR DESCRIPTION
**Pull request by haringsrob**
Avoid loading translation from the DB when the table does not yet exist.

fixes #123
...

### CODE REVIEW

**Comment by AlexisSerneels** [comment]
Thank you!
I've had this issue for ages.
To reproduce the issue, you simply try to run any test using CreateApplication or RefreshDatabase under sqlite and memory.

Your commit is currently missing the import 
```use Illuminate\Support\Facades\Schema;```

**Comment by AlexisSerneels** [comment]
You may also want to use ```getTable()```instead of hardcoding ```language_lines```

Something like:
```
if (! Schema::hasTable((new (config('translation-loader.model')))->getTable())) {
```

**Comment by freekmurze** [comment]
Thanks!

**Comment by dmason30** [comment]
@AlexisSerneels @haringsrob @freekmurze I think this should be reverted, its creates a db query for every time you attempt to translate something?

image

**Pull request merged**
